// Code generated by goyacc -p compile -v /dev/null -o compile_parser.go compile_parser.y. DO NOT EDIT.

//line compile_parser.y:2
package goeval

import __yyfmt__ "fmt"

//line compile_parser.y:2

//line compile_parser.y:6
type compileSymType struct {
	yys   int
	name  string
	node  exprNode
	nodes []exprNode
}

const C_VALUE = 57346
const C_EQ = 57347
const C_NEQ = 57348
const C_GTE = 57349
const C_LTE = 57350
const C_RE = 57351
const C_NRE = 57352
const C_AND = 57353
const C_OR = 57354
const C_NC = 57355
const C_IDENTIFIER = 57356
const C_IN = 57357
const C_CONTAINS = 57358
const C_STARTS_WITH = 57359
const C_ENDS_WITH = 57360
const C_BETWEEN = 57361
const C_WITHIN_LAST = 57362
const C_NOT = 57363
const C_UMINUS = 57364

var compileToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"C_VALUE",
	"C_EQ",
	"C_NEQ",
	"C_GTE",
	"C_LTE",
	"C_RE",
	"C_NRE",
	"C_AND",
	"C_OR",
	"C_NC",
	"C_IDENTIFIER",
	"C_IN",
	"C_CONTAINS",
	"C_STARTS_WITH",
	"C_ENDS_WITH",
	"C_BETWEEN",
	"C_WITHIN_LAST",
	"C_NOT",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"'<'",
	"'>'",
	"'?'",
	"':'",
	"'='",
	"'('",
	"')'",
	"','",
	"'['",
	"']'",
	"'!'",
	"C_UMINUS",
}

var compileStatenames = [...]string{}

const compileEofCode = 1
const compileErrCode = 2
const compileInitialStackSize = 16

//line yacctab:1
var compileExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const compilePrivate = 57344

const compileLast = 152

var compileAct = [...]int8{
	49, 2, 3, 48, 89, 4, 88, 108, 46, 47,
	41, 42, 43, 44, 45, 38, 39, 106, 51, 40,
	23, 58, 59, 60, 61, 109, 89, 62, 63, 64,
	65, 66, 67, 68, 69, 50, 75, 76, 77, 78,
	79, 80, 81, 82, 83, 84, 85, 86, 87, 107,
	89, 105, 89, 7, 90, 91, 104, 89, 93, 92,
	10, 95, 94, 9, 18, 13, 14, 15, 16, 17,
	19, 11, 6, 98, 99, 100, 101, 102, 12, 55,
	1, 20, 0, 0, 8, 0, 5, 0, 0, 0,
	103, 24, 25, 26, 27, 28, 29, 57, 110, 30,
	56, 31, 33, 34, 35, 36, 37, 32, 41, 42,
	43, 44, 45, 38, 39, 7, 52, 40, 21, 22,
	21, 22, 0, 21, 22, 9, 18, 13, 14, 15,
	16, 17, 19, 0, 54, 0, 23, 53, 23, 97,
	96, 23, 0, 20, 0, 0, 8, 70, 71, 72,
	73, 74,
}

var compilePact = [...]int16{
	49, -32768, 112, 86, -32768, 49, 49, -32768, 49, 3,
	-14, 102, 65, -32768, -32768, -32768, -32768, -32768, -32768, -32768,
	49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
	49, 49, 132, 49, 49, 49, 49, 49, 49, 49,
	49, 49, 49, 49, 49, 49, -32768, -32768, -30, 112,
	49, 49, -32768, 111, 49, -32768, 111, 49, 107, -9,
	-9, 109, -12, -12, -12, -12, -12, -12, -12, -12,
	49, 49, 49, 49, 49, -12, -12, -12, -12, -12,
	-32768, -32768, -32768, -32768, -32768, -32768, -32768, -32768, -32768, 49,
	23, 18, -19, 16, -29, -8, -32768, 49, -12, -12,
	-12, -12, -12, 112, -32768, -32768, -32768, -32768, -32768, -32768,
	-32768,
}

var compilePgo = [...]int8{
	0, 80, 0, 5, 2, 78, 71, 3, 60,
}

var compileR1 = [...]int8{
	0, 1, 3, 3, 3, 3, 3, 3, 8, 8,
	8, 8, 8, 8, 8, 6, 6, 6, 6, 5,
	5, 5, 5, 5, 7, 7, 7, 4, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	4, 4, 4, 4, 4, 4, 2, 2, 2, 2,
}

var compileR2 = [...]int8{
	0, 1, 1, 3, 4, 4, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 3, 2, 4, 4, 1,
	1, 2, 4, 4, 0, 1, 3, 1, 2, 2,
	3, 3, 3, 3, 3, 3, 3, 3, 4, 3,
	4, 3, 4, 3, 4, 3, 4, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 1, 3, 3, 5,
}

var compileChk = [...]int16{
	-32768, -1, -2, -4, -3, 37, 23, 4, 35, 14,
	-8, -6, -5, 16, 17, 18, 19, 20, 15, 21,
	32, 11, 12, 29, 5, 6, 7, 8, 9, 10,
	13, 15, 21, 16, 17, 18, 19, 20, 27, 28,
	31, 22, 23, 24, 25, 26, -4, -4, -7, -2,
	32, 32, 14, 35, 32, 14, 35, 32, -2, -2,
	-2, -2, -4, -4, -4, -4, -4, -4, -4, -4,
	15, 16, 17, 18, 19, -4, -4, -4, -4, -4,
	-4, -4, -4, -4, -4, -4, -4, -4, 36, 34,
	-7, -7, -3, -7, -3, -7, 33, 30, -4, -4,
	-4, -4, -4, -2, 33, 33, 36, 33, 36, 33,
	-2,
}

var compileDef = [...]int8{
	0, -2, 1, 56, 27, 0, 0, 2, 24, 19,
	20, 6, 7, 8, 9, 10, 11, 12, 13, 14,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 28, 29, 0, 25,
	24, 24, 16, 0, 24, 21, 0, 24, 0, 57,
	58, 0, 30, 31, 32, 33, 34, 35, 36, 37,
	0, 0, 0, 0, 0, 39, 41, 43, 45, 47,
	48, 49, 50, 51, 52, 53, 54, 55, 3, 0,
	0, 0, 0, 0, 0, 0, 15, 0, 38, 40,
	42, 44, 46, 26, 4, 5, 17, 18, 22, 23,
	59,
}

var compileTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 37, 3, 3, 3, 26, 3, 3,
	32, 33, 24, 22, 34, 23, 3, 25, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 30, 3,
	27, 31, 28, 29, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 35, 3, 36,
}

var compileTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	38,
}

var compileTok3 = [...]int8{
	0,
}

var compileErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	compileDebug        = 0
	compileErrorVerbose = false
)

type compileLexer interface {
	Lex(lval *compileSymType) int
	Error(s string)
}

type compileParser interface {
	Parse(compileLexer) int
	Lookahead() int
}

type compileParserImpl struct {
	lval  compileSymType
	stack [compileInitialStackSize]compileSymType
	char  int
}

func (p *compileParserImpl) Lookahead() int {
	return p.char
}

func compileNewParser() compileParser {
	return &compileParserImpl{}
}

const compileFlag = -32768

func compileTokname(c int) string {
	if c >= 1 && c-1 < len(compileToknames) {
		if compileToknames[c-1] != "" {
			return compileToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func compileStatname(s int) string {
	if s >= 0 && s < len(compileStatenames) {
		if compileStatenames[s] != "" {
			return compileStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func compileErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !compileErrorVerbose {
		return "syntax error"
	}

	for _, e := range compileErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + compileTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(compilePact[state])
	for tok := TOKSTART; tok-1 < len(compileToknames); tok++ {
		if n := base + tok; n >= 0 && n < compileLast && int(compileChk[int(compileAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if compileDef[state] == -2 {
		i := 0
		for compileExca[i] != -1 || int(compileExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; compileExca[i] >= 0; i += 2 {
			tok := int(compileExca[i])
			if tok < TOKSTART || compileExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if compileExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += compileTokname(tok)
	}
	return res
}

func compilelex1(lex compileLexer, lval *compileSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(compileTok1[0])
		goto out
	}
	if char < len(compileTok1) {
		token = int(compileTok1[char])
		goto out
	}
	if char >= compilePrivate {
		if char < compilePrivate+len(compileTok2) {
			token = int(compileTok2[char-compilePrivate])
			goto out
		}
	}
	for i := 0; i < len(compileTok3); i += 2 {
		token = int(compileTok3[i+0])
		if token == char {
			token = int(compileTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(compileTok2[1]) /* unknown char */
	}
	if compileDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", compileTokname(token), uint(char))
	}
	return char, token
}

func compileParse(compilelex compileLexer) int {
	return compileNewParser().Parse(compilelex)
}

func (compilercvr *compileParserImpl) Parse(compilelex compileLexer) int {
	var compilen int
	var compileVAL compileSymType
	var compileDollar []compileSymType
	_ = compileDollar // silence set and not used
	compileS := compilercvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	compilestate := 0
	compilercvr.char = -1
	compiletoken := -1 // compilercvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		compilestate = -1
		compilercvr.char = -1
		compiletoken = -1
	}()
	compilep := -1
	goto compilestack

ret0:
	return 0

ret1:
	return 1

compilestack:
	/* put a state and value onto the stack */
	if compileDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", compileTokname(compiletoken), compileStatname(compilestate))
	}

	compilep++
	if compilep >= len(compileS) {
		nyys := make([]compileSymType, len(compileS)*2)
		copy(nyys, compileS)
		compileS = nyys
	}
	compileS[compilep] = compileVAL
	compileS[compilep].yys = compilestate

compilenewstate:
	compilen = int(compilePact[compilestate])
	if compilen <= compileFlag {
		goto compiledefault /* simple state */
	}
	if compilercvr.char < 0 {
		compilercvr.char, compiletoken = compilelex1(compilelex, &compilercvr.lval)
	}
	compilen += compiletoken
	if compilen < 0 || compilen >= compileLast {
		goto compiledefault
	}
	compilen = int(compileAct[compilen])
	if int(compileChk[compilen]) == compiletoken { /* valid shift */
		compilercvr.char = -1
		compiletoken = -1
		compileVAL = compilercvr.lval
		compilestate = compilen
		if Errflag > 0 {
			Errflag--
		}
		goto compilestack
	}

compiledefault:
	/* default state action */
	compilen = int(compileDef[compilestate])
	if compilen == -2 {
		if compilercvr.char < 0 {
			compilercvr.char, compiletoken = compilelex1(compilelex, &compilercvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if compileExca[xi+0] == -1 && int(compileExca[xi+1]) == compilestate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			compilen = int(compileExca[xi+0])
			if compilen < 0 || compilen == compiletoken {
				break
			}
		}
		compilen = int(compileExca[xi+1])
		if compilen < 0 {
			goto ret0
		}
	}
	if compilen == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			compilelex.Error(compileErrorMessage(compilestate, compiletoken))
			Nerrs++
			if compileDebug >= 1 {
				__yyfmt__.Printf("%s", compileStatname(compilestate))
				__yyfmt__.Printf(" saw %s\n", compileTokname(compiletoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for compilep >= 0 {
				compilen = int(compilePact[compileS[compilep].yys]) + compileErrCode
				if compilen >= 0 && compilen < compileLast {
					compilestate = int(compileAct[compilen]) /* simulate a shift of "error" */
					if int(compileChk[compilestate]) == compileErrCode {
						goto compilestack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if compileDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", compileS[compilep].yys)
				}
				compilep--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if compileDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", compileTokname(compiletoken))
			}
			if compiletoken == compileEofCode {
				goto ret1
			}
			compilercvr.char = -1
			compiletoken = -1
			goto compilenewstate /* try again in the same state */
		}
	}

	/* reduction by production compilen */
	if compileDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", compilen, compileStatname(compilestate))
	}

	compilent := compilen
	compilept := compilep
	_ = compilept // guard against "declared and not used"

	compilep -= int(compileR2[compilen])
	// compilep is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if compilep+1 >= len(compileS) {
		nyys := make([]compileSymType, len(compileS)*2)
		copy(nyys, compileS)
		compileS = nyys
	}
	compileVAL = compileS[compilep+1]

	/* consult goto table to find next state */
	compilen = int(compileR1[compilen])
	compileg := int(compilePgo[compilen])
	compilej := compileg + compileS[compilep].yys + 1

	if compilej >= compileLast {
		compilestate = int(compileAct[compileg])
	} else {
		compilestate = int(compileAct[compilej])
		if int(compileChk[compilestate]) != -compilen {
			compilestate = int(compileAct[compileg])
		}
	}
	// dummy call; replaced with literal code
	switch compilent {

	case 1:
		compileDollar = compileS[compilept-1 : compilept+1]
//line compile_parser.y:26
		{
			compilelex.(*compileLexerAdapter).answer = compileDollar[1].node
			compileVAL.node = compileDollar[1].node
			return 0
		}
	case 2:
		compileDollar = compileS[compilept-1 : compilept+1]
//line compile_parser.y:34
		{
			compileVAL.node = compileDollar[1].node
		}
	case 3:
		compileDollar = compileS[compilept-3 : compilept+1]
//line compile_parser.y:38
		{
			compileVAL.node = arrayNode{items: compileDollar[2].nodes}
		}
	case 4:
		compileDollar = compileS[compilept-4 : compilept+1]
//line compile_parser.y:42
		{
			compileVAL.node = functionNode{name: compileDollar[1].name, args: compileDollar[3].nodes}
		}
	case 5:
		compileDollar = compileS[compilept-4 : compilept+1]
//line compile_parser.y:46
		{
			compileVAL.node = functionNode{name: compileDollar[1].name, args: compileDollar[3].nodes}
		}
	case 8:
		compileDollar = compileS[compilept-1 : compilept+1]
//line compile_parser.y:55
		{
			compileVAL.name = compileDollar[1].name
		}
	case 9:
		compileDollar = compileS[compilept-1 : compilept+1]
//line compile_parser.y:59
		{
			compileVAL.name = compileDollar[1].name
		}
	case 10:
		compileDollar = compileS[compilept-1 : compilept+1]
//line compile_parser.y:63
		{
			compileVAL.name = compileDollar[1].name
		}
	case 11:
		compileDollar = compileS[compilept-1 : compilept+1]
//line compile_parser.y:67
		{
			compileVAL.name = compileDollar[1].name
		}
	case 12:
		compileDollar = compileS[compilept-1 : compilept+1]
//line compile_parser.y:71
		{
			compileVAL.name = compileDollar[1].name
		}
	case 13:
		compileDollar = compileS[compilept-1 : compilept+1]
//line compile_parser.y:75
		{
			compileVAL.name = compileDollar[1].name
		}
	case 14:
		compileDollar = compileS[compilept-1 : compilept+1]
//line compile_parser.y:79
		{
			compileVAL.name = compileDollar[1].name
		}
	case 15:
		compileDollar = compileS[compilept-3 : compilept+1]
//line compile_parser.y:86
		{
			compileVAL.node = compileDollar[2].node
		}
	case 16:
		compileDollar = compileS[compilept-2 : compilept+1]
//line compile_parser.y:90
		{
			compileVAL.node = selectNameNode{base: compileDollar[1].node, key: compileDollar[2].name}
		}
	case 17:
		compileDollar = compileS[compilept-4 : compilept+1]
//line compile_parser.y:94
		{
			compileVAL.node = selectIndexExpr(compileDollar[1].node, compileDollar[3].node)
		}
	case 18:
		compileDollar = compileS[compilept-4 : compilept+1]
//line compile_parser.y:98
		{
			compileVAL.node = callNode{base: compileDollar[1].node, args: compileDollar[3].nodes}
		}
	case 19:
		compileDollar = compileS[compilept-1 : compilept+1]
//line compile_parser.y:105
		{
			compileVAL.node = variableNode{name: compileDollar[1].name}
		}
	case 20:
		compileDollar = compileS[compilept-1 : compilept+1]
//line compile_parser.y:109
		{
			compileVAL.node = variableNode{name: compileDollar[1].name}
		}
	case 21:
		compileDollar = compileS[compilept-2 : compilept+1]
//line compile_parser.y:113
		{
			compileVAL.node = selectNameNode{base: compileDollar[1].node, key: compileDollar[2].name}
		}
	case 22:
		compileDollar = compileS[compilept-4 : compilept+1]
//line compile_parser.y:117
		{
			compileVAL.node = selectIndexExpr(compileDollar[1].node, compileDollar[3].node)
		}
	case 23:
		compileDollar = compileS[compilept-4 : compilept+1]
//line compile_parser.y:121
		{
			compileVAL.node = callNode{base: compileDollar[1].node, args: compileDollar[3].nodes}
		}
	case 24:
		compileDollar = compileS[compilept-0 : compilept+1]
//line compile_parser.y:127
		{
			compileVAL.nodes = nil
		}
	case 25:
		compileDollar = compileS[compilept-1 : compilept+1]
//line compile_parser.y:131
		{
			compileVAL.nodes = []exprNode{compileDollar[1].node}
		}
	case 26:
		compileDollar = compileS[compilept-3 : compilept+1]
//line compile_parser.y:135
		{
			compileVAL.nodes = append(compileVAL.nodes, compileDollar[3].node)
		}
	case 28:
		compileDollar = compileS[compilept-2 : compilept+1]
//line compile_parser.y:141
		{
			compileVAL.node = unaryNode{op: "!", x: compileDollar[2].node}
		}
	case 29:
		compileDollar = compileS[compilept-2 : compilept+1]
//line compile_parser.y:144
		{
			compileVAL.node = unaryNode{op: "-", x: compileDollar[2].node}
		}
	case 30:
		compileDollar = compileS[compilept-3 : compilept+1]
//line compile_parser.y:147
		{
			compileVAL.node = binaryNode{op: opEq, left: compileDollar[1].node, right: compileDollar[3].node}
		}
	case 31:
		compileDollar = compileS[compilept-3 : compilept+1]
//line compile_parser.y:150
		{
			compileVAL.node = binaryNode{op: opNeq, left: compileDollar[1].node, right: compileDollar[3].node}
		}
	case 32:
		compileDollar = compileS[compilept-3 : compilept+1]
//line compile_parser.y:153
		{
			compileVAL.node = binaryNode{op: opGte, left: compileDollar[1].node, right: compileDollar[3].node}
		}
	case 33:
		compileDollar = compileS[compilept-3 : compilept+1]
//line compile_parser.y:156
		{
			compileVAL.node = binaryNode{op: opLte, left: compileDollar[1].node, right: compileDollar[3].node}
		}
	case 34:
		compileDollar = compileS[compilept-3 : compilept+1]
//line compile_parser.y:159
		{
			compileVAL.node = binaryNode{op: opRe, left: compileDollar[1].node, right: compileDollar[3].node}
		}
	case 35:
		compileDollar = compileS[compilept-3 : compilept+1]
//line compile_parser.y:162
		{
			compileVAL.node = binaryNode{op: opNre, left: compileDollar[1].node, right: compileDollar[3].node}
		}
	case 36:
		compileDollar = compileS[compilept-3 : compilept+1]
//line compile_parser.y:165
		{
			compileVAL.node = binaryNode{op: opNc, left: compileDollar[1].node, right: compileDollar[3].node}
		}
	case 37:
		compileDollar = compileS[compilept-3 : compilept+1]
//line compile_parser.y:168
		{
			compileVAL.node = binaryNode{op: opIn, left: compileDollar[1].node, right: compileDollar[3].node}
		}
	case 38:
		compileDollar = compileS[compilept-4 : compilept+1]
//line compile_parser.y:171
		{
			compileVAL.node = binaryNode{op: opNotIn, left: compileDollar[1].node, right: compileDollar[4].node}
		}
	case 39:
		compileDollar = compileS[compilept-3 : compilept+1]
//line compile_parser.y:174
		{
			compileVAL.node = binaryNode{op: opContains, left: compileDollar[1].node, right: compileDollar[3].node}
		}
	case 40:
		compileDollar = compileS[compilept-4 : compilept+1]
//line compile_parser.y:177
		{
			compileVAL.node = binaryNode{op: opNotContains, left: compileDollar[1].node, right: compileDollar[4].node}
		}
	case 41:
		compileDollar = compileS[compilept-3 : compilept+1]
//line compile_parser.y:180
		{
			compileVAL.node = binaryNode{op: opStartsWith, left: compileDollar[1].node, right: compileDollar[3].node}
		}
	case 42:
		compileDollar = compileS[compilept-4 : compilept+1]
//line compile_parser.y:183
		{
			compileVAL.node = binaryNode{op: opNotStartsWith, left: compileDollar[1].node, right: compileDollar[4].node}
		}
	case 43:
		compileDollar = compileS[compilept-3 : compilept+1]
//line compile_parser.y:186
		{
			compileVAL.node = binaryNode{op: opEndsWith, left: compileDollar[1].node, right: compileDollar[3].node}
		}
	case 44:
		compileDollar = compileS[compilept-4 : compilept+1]
//line compile_parser.y:189
		{
			compileVAL.node = binaryNode{op: opNotEndsWith, left: compileDollar[1].node, right: compileDollar[4].node}
		}
	case 45:
		compileDollar = compileS[compilept-3 : compilept+1]
//line compile_parser.y:192
		{
			compileVAL.node = binaryNode{op: opBetween, left: compileDollar[1].node, right: compileDollar[3].node}
		}
	case 46:
		compileDollar = compileS[compilept-4 : compilept+1]
//line compile_parser.y:195
		{
			compileVAL.node = binaryNode{op: opNotBetween, left: compileDollar[1].node, right: compileDollar[4].node}
		}
	case 47:
		compileDollar = compileS[compilept-3 : compilept+1]
//line compile_parser.y:198
		{
			compileVAL.node = binaryNode{op: opWithinLast, left: compileDollar[1].node, right: compileDollar[3].node}
		}
	case 48:
		compileDollar = compileS[compilept-3 : compilept+1]
//line compile_parser.y:201
		{
			compileVAL.node = binaryNode{op: opLt, left: compileDollar[1].node, right: compileDollar[3].node}
		}
	case 49:
		compileDollar = compileS[compilept-3 : compilept+1]
//line compile_parser.y:204
		{
			compileVAL.node = binaryNode{op: opGt, left: compileDollar[1].node, right: compileDollar[3].node}
		}
	case 50:
		compileDollar = compileS[compilept-3 : compilept+1]
//line compile_parser.y:207
		{
			compileVAL.node = binaryNode{op: opMatch, left: compileDollar[1].node, right: compileDollar[3].node}
		}
	case 51:
		compileDollar = compileS[compilept-3 : compilept+1]
//line compile_parser.y:210
		{
			compileVAL.node = binaryNode{op: opAdd, left: compileDollar[1].node, right: compileDollar[3].node}
		}
	case 52:
		compileDollar = compileS[compilept-3 : compilept+1]
//line compile_parser.y:213
		{
			compileVAL.node = binaryNode{op: opSub, left: compileDollar[1].node, right: compileDollar[3].node}
		}
	case 53:
		compileDollar = compileS[compilept-3 : compilept+1]
//line compile_parser.y:216
		{
			compileVAL.node = binaryNode{op: opMulti, left: compileDollar[1].node, right: compileDollar[3].node}
		}
	case 54:
		compileDollar = compileS[compilept-3 : compilept+1]
//line compile_parser.y:219
		{
			compileVAL.node = binaryNode{op: opDiv, left: compileDollar[1].node, right: compileDollar[3].node}
		}
	case 55:
		compileDollar = compileS[compilept-3 : compilept+1]
//line compile_parser.y:222
		{
			compileVAL.node = binaryNode{op: opMod, left: compileDollar[1].node, right: compileDollar[3].node}
		}
	case 57:
		compileDollar = compileS[compilept-3 : compilept+1]
//line compile_parser.y:229
		{
			compileVAL.node = binaryNode{op: opAnd, left: compileDollar[1].node, right: compileDollar[3].node}
		}
	case 58:
		compileDollar = compileS[compilept-3 : compilept+1]
//line compile_parser.y:232
		{
			compileVAL.node = binaryNode{op: opOr, left: compileDollar[1].node, right: compileDollar[3].node}
		}
	case 59:
		compileDollar = compileS[compilept-5 : compilept+1]
//line compile_parser.y:235
		{
			compileVAL.node = ternaryNode{cond: compileDollar[1].node, truthy: compileDollar[3].node, falsy: compileDollar[5].node}
		}
	}
	goto compilestack /* stack new state and value */
}
